# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - wordle-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install and zip backend only
        run: |
          cd backend
          npm install
          zip -r ../release.zip .

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip for deployment
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3003F0EF497541879B0DB074DFFDFEC0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D31752277BC749AF88D29A86CF632BE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D4CEA5A11B064A79B7049A672CB9E2F6 }}

      - name: Deploy to Azure Web App (backend only)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wordle-backend'
          slot-name: 'Production'
          package: .
